// Console.WriteLine("Привет от ИСП-241");
// Console.WriteLine("Автор: Бараков Олег");
// Console.WriteLine("Год: 2026");
// int age = 20;
// double gpa = 4.5;
// bool isStudent = true;
// string name = "Иван";
// Console.WriteLine(name);
// Console.WriteLine(age);
// Console.WriteLine(gpa);
// Console.WriteLine(isStudent);
// var city = "Москва";
// var year = 2026;
// var pi = 3.14159;
// var isActive = true;
// string myName = "Иван";
// int myAge = 20;
// string myGroup = "ИСП-241";
// Console.WriteLine($"меня зовут {myName}, мне {myAge} лет, я учусь в группе {myGroup}.");
// Console.Write("Введите ваше имя: ");
// string name2 = Console.ReadLine();
// Console.WriteLine($"Привет, {name2}!");
// Console.Write("Введите ваш возраст: ");
// string input = Console.ReadLine();
// int age2 = int.Parse(input);
// Console.WriteLine($"Через 10 лет вам будет {age2 + 10} лет.");
// int x = 10;
// int y = 3;
// Console.WriteLine(x + y);
// Console.WriteLine(x - y);
// Console.WriteLine(x * y);
// Console.WriteLine(x / y);
// Console.WriteLine(x % y);
string firstName = "Олег";
string lastName = "Бараков";
string group = "ИСП-241";
int birthYear = 2007;
double gpa = 4.4;
bool hasSchalarshop = true;
int currentYear = 2026;
int age = currentYear - birthYear;
Console.WriteLine("Студентическое удостоверение");
Console.WriteLine($"Имя: {firstName} {lastName}");
Console.WriteLine($"Группа: {group}");
Console.WriteLine($"Возраст: {age} лет");
Console.WriteLine($"Средний балл: {gpa}");
Console.WriteLine($"Стипендия: {hasSchalarshop}");
Console.Write("\nВведите ваш любимый предмет: ");
string subject = Console.ReadLine();
Console.WriteLine($"Отлично! {firstName} любит {subject}.");